# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f47a7f8aeef324d7bd01365ebe4f48d1195d26cfd470522a86f90689c64a32d2d3c43b117823fa61e7c3014e9c880d887ab0ba8400745239cd60907113121e4

test:
  secret_key_base: 2e4c8a7e1002c540daaf5a3822d5f2b6dd233a205e9aebd993f0c2dc6ff88bdead81427f76f200cbac3c8cbe59b0fc00869f7ed9c7a632321b5a34ca8ba12faa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
